import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qt import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(373, 343)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pb_0 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_0.sizePolicy().hasHeightForWidth())
        self.pb_0.setSizePolicy(sizePolicy)
        self.pb_0.setMinimumSize(QtCore.QSize(55, 55))
        self.pb_0.setMaximumSize(QtCore.QSize(55, 55))
        self.pb_0.setObjectName("pb_0")
        self.gridLayout.addWidget(self.pb_0, 0, 0, 1, 1)
        self.pb_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pb_1.setMinimumSize(QtCore.QSize(55, 55))
        self.pb_1.setMaximumSize(QtCore.QSize(55, 55))
        self.pb_1.setObjectName("pb_1")
        self.gridLayout.addWidget(self.pb_1, 0, 1, 1, 1)
        self.pb_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pb_2.setMinimumSize(QtCore.QSize(55, 55))
        self.pb_2.setMaximumSize(QtCore.QSize(55, 55))
        self.pb_2.setObjectName("pb_2")
        self.gridLayout.addWidget(self.pb_2, 0, 2, 1, 1)
        self.pb_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pb_3.setMinimumSize(QtCore.QSize(55, 55))
        self.pb_3.setMaximumSize(QtCore.QSize(55, 55))
        self.pb_3.setObjectName("pb_3")
        self.gridLayout.addWidget(self.pb_3, 0, 3, 1, 1)
        self.pb_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pb_4.setMinimumSize(QtCore.QSize(55, 55))
        self.pb_4.setMaximumSize(QtCore.QSize(55, 55))
        self.pb_4.setObjectName("pb_4")
        self.gridLayout.addWidget(self.pb_4, 1, 0, 1, 1)
        self.pb_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pb_5.setMinimumSize(QtCore.QSize(55, 55))
        self.pb_5.setMaximumSize(QtCore.QSize(55, 55))
        self.pb_5.setObjectName("pb_5")
        self.gridLayout.addWidget(self.pb_5, 1, 1, 1, 1)
        self.pb_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pb_6.setMinimumSize(QtCore.QSize(55, 55))
        self.pb_6.setMaximumSize(QtCore.QSize(55, 55))
        self.pb_6.setObjectName("pb_6")
        self.gridLayout.addWidget(self.pb_6, 1, 2, 1, 1)
        self.pb_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pb_7.setMinimumSize(QtCore.QSize(55, 55))
        self.pb_7.setMaximumSize(QtCore.QSize(55, 55))
        self.pb_7.setObjectName("pb_7")
        self.gridLayout.addWidget(self.pb_7, 1, 3, 1, 1)
        self.pb_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pb_8.setMinimumSize(QtCore.QSize(55, 55))
        self.pb_8.setMaximumSize(QtCore.QSize(55, 55))
        self.pb_8.setObjectName("pb_8")
        self.gridLayout.addWidget(self.pb_8, 2, 0, 1, 1)
        self.pb_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pb_9.setMinimumSize(QtCore.QSize(55, 55))
        self.pb_9.setMaximumSize(QtCore.QSize(55, 55))
        self.pb_9.setObjectName("pb_9")
        self.gridLayout.addWidget(self.pb_9, 2, 1, 1, 1)
        self.pb_A = QtWidgets.QPushButton(self.centralwidget)
        self.pb_A.setMinimumSize(QtCore.QSize(55, 55))
        self.pb_A.setMaximumSize(QtCore.QSize(55, 55))
        self.pb_A.setObjectName("pb_A")
        self.gridLayout.addWidget(self.pb_A, 2, 2, 1, 1)
        self.pb_B = QtWidgets.QPushButton(self.centralwidget)
        self.pb_B.setMinimumSize(QtCore.QSize(55, 55))
        self.pb_B.setMaximumSize(QtCore.QSize(55, 55))
        self.pb_B.setObjectName("pb_B")
        self.gridLayout.addWidget(self.pb_B, 2, 3, 1, 1)
        self.pb_C = QtWidgets.QPushButton(self.centralwidget)
        self.pb_C.setMinimumSize(QtCore.QSize(55, 55))
        self.pb_C.setMaximumSize(QtCore.QSize(55, 55))
        self.pb_C.setObjectName("pb_C")
        self.gridLayout.addWidget(self.pb_C, 3, 0, 1, 1)
        self.pb_D = QtWidgets.QPushButton(self.centralwidget)
        self.pb_D.setMinimumSize(QtCore.QSize(55, 55))
        self.pb_D.setMaximumSize(QtCore.QSize(55, 55))
        self.pb_D.setObjectName("pb_D")
        self.gridLayout.addWidget(self.pb_D, 3, 1, 1, 1)
        self.pb_E = QtWidgets.QPushButton(self.centralwidget)
        self.pb_E.setMinimumSize(QtCore.QSize(55, 55))
        self.pb_E.setMaximumSize(QtCore.QSize(55, 55))
        self.pb_E.setObjectName("pb_E")
        self.gridLayout.addWidget(self.pb_E, 3, 2, 1, 1)
        self.pb_F = QtWidgets.QPushButton(self.centralwidget)
        self.pb_F.setMinimumSize(QtCore.QSize(55, 55))
        self.pb_F.setMaximumSize(QtCore.QSize(55, 55))
        self.pb_F.setObjectName("pb_F")
        self.gridLayout.addWidget(self.pb_F, 3, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 373, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pb_0.setText(_translate("MainWindow", "pb_0"))
        self.pb_1.setText(_translate("MainWindow", "pb_1"))
        self.pb_2.setText(_translate("MainWindow", "pb_2"))
        self.pb_3.setText(_translate("MainWindow", "pb_3"))
        self.pb_4.setText(_translate("MainWindow", "pb_4"))
        self.pb_5.setText(_translate("MainWindow", "pb_5"))
        self.pb_6.setText(_translate("MainWindow", "pb_6"))
        self.pb_7.setText(_translate("MainWindow", "pb_7"))
        self.pb_8.setText(_translate("MainWindow", "pb_8"))
        self.pb_9.setText(_translate("MainWindow", "pb_9"))
        self.pb_A.setText(_translate("MainWindow", "pb_A"))
        self.pb_B.setText(_translate("MainWindow", "pb_B"))
        self.pb_C.setText(_translate("MainWindow", "pb_C"))
        self.pb_D.setText(_translate("MainWindow", "pb_D"))
        self.pb_E.setText(_translate("MainWindow", "pb_E"))
        self.pb_F.setText(_translate("MainWindow", "pb_F"))



class ExampleApp(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

        _list = ['0', '1', '2', '3', '4', '5', '6', '7',
                '8',  '9', 'A', 'B', 'C', 'D', 'E', 'F']
        for n in _list:
            getattr(self, 'pb_%s' % n).pressed.connect(lambda v=n: self.numberClicked(v))

    def numberClicked(self, v):
        print(v)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    a_window = ExampleApp()
    a_window.show()
    sys.exit(app.exec_())